export const SETTINGS = [
    {
        name: 'Tag/Taglar',
        value: 'tags',
        description: 'Sunucu tagını ayarlarsınız.',
        type: 'string',
        isMultiple: true,
        isNumber: false,
    },
    {
        name: 'Yetkili Alma Puanı',
        value: 'staffTakePoints',
        description: 'Yetkili alınca eklenecek puan.',
        type: 'string',
        isMultiple: false,
        isNumber: true,
    },
    {
        name: 'Kayıt Puanı',
        value: 'registerPoints',
        description: 'Kayıt yapınca eklenecek puan.',
        type: 'string',
        isMultiple: false,
        isNumber: true,
    },
    {
        name: 'Taglı Alma Puan',
        value: 'taggedPoints',
        description: 'Taglı alınca eklenecek puan.',
        type: 'string',
        isMultiple: false,
        isNumber: true,
    },
    {
        name: 'En Alt Yetkili Rolü',
        value: 'minStaffRole',
        description: 'En alt yetkili rollerini ayarlarsınız.',
        type: 'role',
        isMultiple: false,
    },
    {
        name: 'Chat Kanalı',
        value: 'chatChannel',
        description: 'Chat kanalını belirlersiniz.',
        type: 'channel',
        isParent: false,
        isVoice: false,
    },
    {
        name: 'Chat Yetkili Rolleri',
        value: 'chatStaffs',
        description: 'Chat sorumlu rollerini belirlersiniz.',
        type: 'role',
        isMultiple: true,
    },
    {
        name: 'Yetki Rolleri',
        description: 'Yetkililerin kasacağı puanlarla alacağı roller.',
        type: 'ranks',
        value: 'ranks',
    },
    {
        name: 'Mesaj Puanı',
        value: 'messagePoint',
        description: 'Genel sohbete attığında alacağı puan.',
        type: 'string',
        isMultiple: false,
        isNumber: true,
    },
    {
        name: 'Yetkili Mesaj Puanı',
        value: 'messageStaffPoint',
        description: 'Chat yetkililerin genel sohbete attığında alacağı puan.',
        type: 'string',
        isMultiple: false,
        isNumber: true,
    },
    {
        name: 'Görev',
        description: 'Yetkililerin yapacağı görevler.',
        type: 'tasks',
        value: 'tasks',
    },
    {
        name: 'Kanala Özel Puan',
        description: 'Belirtilen kanala ve role sahip birinin alacağı puan.',
        type: 'responsibilitys',
        value: 'responsibilitys',
    },
    {
        name: 'Davet Puanı',
        value: 'invitePoint',
        description: 'Davet yaptığında alacağı puan.',
        type: 'string',
        isMultiple: false,
        isNumber: true,
    },
    {
        name: 'Sleep Puanı',
        value: 'sleepPoint',
        description: 'Ayarlı olmayan kanallarda alacağı puan.',
        type: 'string',
        isMultiple: false,
        isNumber: true,
    },
    {
        name: 'Public Puanı',
        value: 'publicPoint',
        description: 'Public odasında alacağı puan.',
        type: 'string',
        isMultiple: false,
        isNumber: true,
    },
    {
        name: 'AFK Odası',
        value: 'afkRoom',
        description: 'AFK odasını belirtin.',
        type: 'channel',
        isParent: false,
        isVoice: true,
    },
    {
        name: 'Public Kategorisi',
        value: 'publicCategory',
        description: 'Public kategorisini belirtin.',
        type: 'channel',
        isParent: true,
        isVoice: false,
    },
    {
        name: 'Katıldı Rolü',
        value: 'meetingRole',
        description: 'Toplantı katıldı rolünü ayarlarsınız.',
        type: 'role',
        isMultiple: false,
    },
    {
        name: 'Toplantı Odası Puanı',
        value: 'meetingPoint',
        description: 'Toplantı odasında alacağı puan.',
        type: 'string',
        isMultiple: false,
        isNumber: true,
    },
    {
        name: 'Susturma/Kulaklık',
        value: 'noMute',
        description: 'Susturması veya kulaklığı kapalıysa saysın mı?',
        type: 'boolean',
    },
];
